"""Remove Staff model and role

Revision ID: 963a9687fb3f
Revises: 5a8cd0c0cbc8
Create Date: 2025-04-12 11:47:16.937192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963a9687fb3f'
down_revision = '5a8cd0c0cbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
